services:
  taller:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: taller-app
    # env_file:
    #   - .env
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload